name: dart_dgc_validate
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dart_base45: ^1.0.0
  dart_cose: ^1.0.2
  cbor: ^4.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
