name: dart_dgc_validate
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_base45: #^1.0.0
    path: ../dart_base45
  dart_cose: 
    path: ../dart_cose
  cbor: ^4.0.1
  x509: #^0.2.2
    path: ../x509
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  convert: ^3.0.0
